before_script:
    - angr-test sync hard

fuzzer:
    script: "angr-test fuzzer"
    tags: [angr]

driller:
  script: "angr-test driller"
  tags: [angr]

lint:
    script: "angr-test lint"
    tags: [angr]
